services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: eshopdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5238:5238"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=eshopdb;Username=postgres;Password=postgres123
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=TwojSuperTajnyKluczJWTKtoryMusiMiecMin32Znaki!
      - Jwt__Issuer=EShop
      - Jwt__Audience=EShopUsers
      - Stripe__SecretKey=${STRIPE_SECRET_KEY}
      - Stripe__WebhookSecret=${STRIPE_WEBHOOK_SECRET}
      - Stripe__SuccessUrl=http://localhost:4200/orders
      - Stripe__CancelUrl=http://localhost:4200/cart
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/eshop-ui
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata: